apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-analyzer.fullname" . }}
  labels:
    {{- include "kube-analyzer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-analyzer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-analyzer.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-analyzer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--in-cluster"
            - "--analysis-type"
            - "{{ .Values.analysis.type }}"
            - "--prometheus-url"
            - "{{ .Values.prometheus.url }}"
            - "--output-format"
            - "{{ .Values.reporting.format }}"
            - "--output-dir"
            - "/app/reports"
            {{- if .Values.analysis.excludeNamespaces }}
            - "--exclude-namespaces"
            {{- range .Values.analysis.excludeNamespaces }}
            - "{{ . }}"
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.reporting.persistentVolume.enabled }}
            - name: reports-volume
              mountPath: /app/reports
            {{- end }}
      volumes:
        {{- if .Values.reporting.persistentVolume.enabled }}
        - name: reports-volume
          persistentVolumeClaim:
            claimName: {{ include "kube-analyzer.fullname" . }}-reports
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
